// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErh8OFL_heLstXLKNc0u_WXjBSi7q6lk',
    appId: '1:608194468221:web:0bf1b159a6807c16ff9414',
    messagingSenderId: '608194468221',
    projectId: 'cycle-8e30e',
    authDomain: 'cycle-8e30e.firebaseapp.com',
    storageBucket: 'cycle-8e30e.appspot.com',
    measurementId: 'G-T182Y6XTBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpv7nUukZSB8mxm1S3LRy-X5X7mnTbdo',
    appId: '1:608194468221:android:3fbe61659cc0b806ff9414',
    messagingSenderId: '608194468221',
    projectId: 'cycle-8e30e',
    storageBucket: 'cycle-8e30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgUaH_Q9Hg1ZL4qsRE_oXsrk5tHDb-Is',
    appId: '1:608194468221:ios:f62703c33b2d25e4ff9414',
    messagingSenderId: '608194468221',
    projectId: 'cycle-8e30e',
    storageBucket: 'cycle-8e30e.appspot.com',
    iosBundleId: 'com.oceansoft.cycle',
  );
}
